enum OwnerHashStatus {
  RUNNING = "RUNNING",
  SOMEONE_ELSE_HOLDS_LOCK = "SOMEONE_ELSE_HOLDS_LOCK",
  NO_KEY = "NO_KEY",
  NO_RUNNING_PROCESS = "NO_RUNNING_PROCESS",
  MALFORMED_OWNER_HASH = "MALFORMED_OWNER_HASH",
}

export default OwnerHashStatus;
